### ISSUE TITLE
是否可以支持成员变量为对象时，也可以存储在数据库里呢？

### ISSUE THREAD

**Issue by hh404** [bing6/FMDBDataTable#12]
例如：
@interface Test : NSObject
@property (nonatomic, strong) NSString *strTest;
@property (nonatomic, strong) Message *message;
@property (nonatomic, strong) Users *users;
@end
可以直接调用  
 [icmd saveChangesInBackground:^{
        NSLog(@"批量数据提交完成");
    }];
这种也可以直接保存的，因为coredata是支持这种操作的，在比较特殊的时候不想建立多个表关联，这种做法也是挺方便的。

我自己做了测试，在Users实现：
- (void)encodeWithCoder:(NSCoder *)aCoder{
  [aCoder encodeObject:[NSNumber numberWithInteger:_userId] forKey:@"userId"];
  [aCoder encodeObject:_nickname forKey:@"nickname"];
  [aCoder encodeObject:_sex forKey:@"sex"];
  [aCoder encodeObject:_other forKey:@"other"];
  }
- (id)initWithCoder:(NSCoder *)aDecoder{
  self = [super init];
  if(self != nil){
      _userId = [[aDecoder decodeObjectForKey:@"userId"] integerValue];
      _nickname = [aDecoder decodeObjectForKey:@"nickname"];
      _sex = [aDecoder decodeObjectForKey:@"sex"];
      _other = [aDecoder decodeObjectForKey:@"other"];
  }
  return self;
  }

在FMDTInsertCommand.m里边修改
- (NSArray _)getObjectValues:(FMDTObject *)obj {
  NSMutableArray *result = [NSMutableArray new];
  for (FMDTSchemaField *entry in self.schema.fields) {
      id val = [obj valueForKey:entry.objName];
      NSString *type = [[entry.objType componentsSeparatedByString:@"\""] objectAtIndex:1];
      const char_ cType = [type UTF8String];
      Class c = objc_getClass(cType);
      if (val) {
          if (FMDT_IsCollectionObject(entry.objType)) {
              NSData *data = [NSJSONSerialization dataWithJSONObject:val
                                                             options:NSJSONWritingPrettyPrinted
                                                               error:nil];
              if (data) {
                  NSString *str = [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding];
                  [result addObject:str];
              } else {
                  [result addObject:[NSNull null]];
              }
          } else if (FMDT_IsDateObject(entry.objType)) {
              [result addObject:@([val timeIntervalSince1970])];
          }
          else if ([c isSubclassOfClass:[FMDTObject class]])
          {
              NSData *data = [NSKeyedArchiver archivedDataWithRootObject:val];
              if(data)
              {
                  [result addObject:data];
              }
              else
              {
                  [result addObject:[NSNull null]];
              }
          }
          else {
              [result addObject:val];
          }
      } else {
          [result addObject:[NSNull null]];
      }
  }
  return result;
  }

在FMDTSelectCommand.m做对应的NSKeyedUnarchiver即可实现这个功能。是否可以考虑增加上呢？

**Comment by bing6** [comment]
对于这个问题，我觉得得是不是可以这样做
1.首先定义集合类型的属性(NSDictionary,NSMutableDictionary,NSArray,NSMutableArray)
2.在类中定义转换方法。这件事你也可以在扩展类中做。
