### ISSUE TITLE
saveChangesInBackground 这个函数是否是有bug?其实它并不是在子线程里执行，一般还是在主线程

### ISSUE THREAD

**Issue by hh404** [bing6/FMDBDataTable#13]
saveChangesInBackground 这个函数是否是有bug?其实它并不是在子线程里执行，一般还是在主线程。这个自定义fmdb的queue只是一个串行自定义队列，会在当前线程执行。也就是说我们按照demo运行在 NSLog处打断点可以看出，实际上是在主线程里执行的
   [icmd saveChangesInBackground:^{
        NSLog(@"批量数据提交完成");
    }];

要在子线程执行，需要修改对应的代码，例如FMDTInsertCommand类修改为：
- (void)saveChangesInBackground:(void (^)())complete {
  dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
      FMDatabaseQueue *queue = [FMDatabaseQueue databaseQueueWithPath:self.schema.storage];
      queue = [[FMDTManager shared] queue];
  
  ```
  [queue inTransaction:^(FMDatabase *db, BOOL *rollback) {
      @try {
          for (FMDTObject *entry in self.dataArray) {
              NSArray *array = [self getObjectValues:entry];
              NSString *statement = nil;
              if (self.relpace) {
                  statement = self.schema.statementReplace;
              } else {
                  statement = self.schema.statementInsert;
              }
              [db executeUpdate:statement withArgumentsInArray:array];
          }
      }
      @catch (NSException *exception) {
          *rollback = YES;
      }
  
      [self.dataArray removeAllObjects];
  
      if (complete) {
          complete();
      }
  }];
  ```
  
  });
  }
  这样就在子线程里运行了，是否我的用法有问题？

**Comment by bing6** [comment]
FMDatabaseQueue确实不是在子线程运行的，需要在外边包一层。

**Comment by bing6** [comment]
感谢你的反馈，最新版本已修改
