### ISSUE TITLE
sql update error 

### ISSUE THREAD

**Issue by bing050802** [bing6/FMDBDataTable#14]
error descritions: 
DB Error: 1 "near "msgNum": syntax error"
 DB Query: update [YHZDBSendInfoRemind] set readTime=:readTime msgNum=:msgNum where  remindId = '1498' and serverId = '681'
 DB Path: 

update two fields in same time would make error like this 
  FMDTUpdateCommand *cmd = [[YHZDBSet shared].sendInfoRemind createUpdateCommand];
    [cmd where:@"remindId" equalTo:object[@"remindId"]];
    [cmd where:@"serverId" equalTo:object[@"serverId"]];
    [cmd fieldWithKey:@"readTime" val:@"1"];
    [cmd fieldWithKey:@"msgNum" val:@"0"];

I  found this error in file FMDTUpdateCommand line 180
    for (NSString *key in self.dataDict.allKeys) {
        [sql appendFormat:@" %@=:%@", key, key];
    }

many keys in sql words need "," so 我change this

```
for (NSString *key in self.dataDict.allKeys) {
    [sql appendFormat:@" %@=:%@,", key, key];
}
[sql deleteCharactersInRange:NSMakeRange(sql.length-1, 1)];
```

在w3cshool里面，
更新某一行中的若干列
我们会修改地址（address），并添加城市名称（city）：
UPDATE Person SET Address = 'Zhongshan 23', City = 'Nanjing'
WHERE LastName = 'Wilson'

必须多个并列的时候需要加“,”,源代码中没有加，所以在同时更新多个列时候会出错

**Comment by bing6** [comment]
这个问题已经修复了
