### ISSUE TITLE
请教一下大神

### ISSUE THREAD

**Issue by aihuimoushuixiao** [bing6/FMDBDataTable#15]
修改数据库的数据，只能一个，一个字段的修改吗，如果需要同时修改几个字段，用下面这样修改几个字段，在真机上没有效果啊
[ucmd2 fieldWithKey:@"sex" val:@"男"];
[ucmd2 fieldWithKey:@"nickname" val:@"小明"];

**Comment by bing6** [comment]
这里有个BUG，已经修改了，可以更新一下最新版本

**Comment by bing050802** [comment]
我觉得修改的bug是不是会多了个，
    for (NSString *key in self.dataDict.allKeys) {
        [sql appendFormat:@" %@=:%@,", key, key];
    }
    [sql deleteCharactersInRange:NSMakeRange(sql.length-1, 1)];

经过一个一个循环，最后一个应该不要“，”

**Comment by bing6** [comment]
是这样的

**Comment by aihuimoushuixiao** [comment]
可以了，多谢，非常好用
